import argparse
import asyncio
import copy
import json
import logging
import os
import queue as queue_module
from collections import defaultdict, deque
import socket as socket_module
import signal
import sys
import threading
import time
from datetime import datetime
from functools import partial
from pathlib import Path

import numpy as np
from pyproj import Transformer

from marker import Markers, map_detected_markers
from time import time_ns
from detection import detect_markers
from hud import draw_monitor_window, draw_status_window
from automatic_calibration import calibrate_fixed_rig
from calibration_handler import load_calibration_markers
from camera_stitching import setup_camera_transforms, process_and_join_streams
from pixel_to_utm import (
    BasemapCalibrationPoint,
    BasemapHomography,
    create_basemap_homography,
    direction_through_homography,
    ground_scale,
    project_utm_to_pixels,
)
from table_to_geojson import markers_json_to_geojson
from physical_building_catalog import (
    BUILDING_CALIBRATION_MESSAGE_FIELDS,
    MODEL_SCALE,
    apply_building_calibration,
    calibration_as_message_fields,
    calibration_from_message,
    building_feature,
    load_catalog,
    marker_index,
    model_scale_factor,
    save_catalog,
)
from building_registration import MINIMUM_REFERENCE_SAMPLES, SIGHTING_WINDOW_SECONDS
from building_registration import (
    catalog_with_entry,
    marker_on_target,
    marker_to_register,
    markers_on_the_table,
    named_marker,
    recent_rotations,
    reference_rotation_from_samples,
    registered_entry,
)
from calibration_contract import MAP_CALIBRATION_MARKER_IDS
from marker import IGNORED_MARKER_ID
from session_store import BuildingCalibration, SessionStore

#: WGS84 -> UTM 32N, for turning the frontend's alignment-target position into the frame the
#: homography speaks. Built once: constructing a Transformer parses CRS definitions.
_WGS84_TO_UTM = Transformer.from_crs("EPSG:4326", "EPSG:25832", always_xy=True)
import websockets

# Windows consoles default to a non-UTF-8 codepage (e.g. cp1252), which
# crashes on the emoji used throughout this codebase's print() calls.
sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

# Global variable for stitching setup
stitching_setup = None

# Basemap homography computed from the web client's map_calibration message.
# None until the web client sends calibration points, in which case tracking
# matches are sent as GeoJSON (see handle_web_client); otherwise a plain
# marker dict is sent.
basemap_homography: BasemapHomography | None = None

# How far catalog geometry must shrink to sit on top of its 1:500 block under the *current*
# calibration (physical_building_catalog.model_scale_factor). Derived from the homography the
# moment one is accepted -- never sent by the frontend, never measured by hand -- and reset to
# None alongside it, so a stale factor can never outlive the calibration it was derived from.
global_model_scale_factor: float | None = None

# The session_store id of the calibration currently in force. Generated by Python from the
# accepted handshake (the frontend has no session id and sends none), so every building
# measurement can be filed against the homography it was actually measured under.
current_session_id: str | None = None

# Raw TCP socket used only for the "unity" client. Created in setup_pixel_socket().
pixel_socket = None
PIXEL_SOCKET_SETTINGS = ("localhost", 8052)

loop = asyncio.new_event_loop()

WEB_WS_HOST = "0.0.0.0"
WEB_WS_PORT = 8053

# Marker snapshots (dicts) produced by the detection thread, consumed by
# whichever client (unity/web) is sending tracking updates. Bounded to 1 so
# stale snapshots get replaced instead of piling up if a consumer falls behind.
tracking_queue: "queue_module.Queue[dict]" = queue_module.Queue(maxsize=1)

# Dedicated calibration log: every accepted/rejected map_calibration message gets its own
# timestamped line here, separate from the console (which is too noisy from the detection
# loop to spot a calibration change in). One file per server run under logs/calibration/.
# Anchored to this script's own directory (not the process's cwd) so the folder always
# lands next to server.py regardless of where the server is launched from.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PHYSICAL_BUILDING_CATALOG_PATH = os.path.join(_SCRIPT_DIR, "physical-building-catalog.json")

# Where an accepted `building_calibration` is written. Deliberately *not* the runtime catalog
# above: `building_catalog/publish-to-runtime.ps1` promotes this file to that one, so an operator
# saving a value mid-session cannot corrupt the catalog the running server booted from. The
# in-memory catalog is updated too, so the nudge is visible on the projection immediately -- it
# just does not become the next boot's default until someone publishes it.
WORKING_BUILDING_CATALOG_PATH = os.path.join(
    _SCRIPT_DIR, "building_catalog", "physical-building-catalog.json"
)
physical_building_catalog = load_catalog(Path(PHYSICAL_BUILDING_CATALOG_PATH))
physical_buildings_by_marker = marker_index(physical_building_catalog)
_warned_unknown_marker_ids: set[int] = set()

# Where each building marker was last seen in table-pixel space, and when. Python owns pixel
# space -- once a homography exists the frontend only ever sees WGS84 -- so the server stamps
# every recorded measurement with its own latest reading rather than trusting a value echoed
# back to it.
#
# The timestamp is not bookkeeping: `table_x_px`/`table_y_px` exist to tell a position-dependent
# homography error apart from a per-building one, so a measurement filed at a position the block
# was not actually at corrupts the exact signal the whole record is kept for. A marker that has
# stopped being seen keeps its last reading here forever otherwise, and a building left in
# `session.tracking` could be saved against a position from a previous sitting.
latest_table_pixel_positions: dict[int, tuple[float, float, float]] = {}

#: Marker ids registration must never offer as a candidate building marker: the four (now nine)
#: the Table window projects for map calibration, and the sentinel `marker.py` reserves. Derived
#: from the contracts that own them rather than restated, so growing the calibration grid cannot
#: silently make one of its markers registerable as a building.
RESERVED_MARKER_IDS = set(MAP_CALIBRATION_MARKER_IDS) | {IGNORED_MARKER_ID}

#: The source footprints registration builds catalog entries from -- the same file the frontend
#: bundles and draws its alignment target from, so the heading the operator lines the block up
#: against and the heading written into the catalog are the same number by construction.
SOURCE_BUILDINGS_PATH = os.path.join(_SCRIPT_DIR, "building_catalog", "buildings_all.geojson")

#: Recent `(seen_at, heading)` readings per marker, newest last, for registration's circular mean.
#:
#: A buffer rather than the latest single frame because one frame of ArUco corner detection
#: carries a degree or more of noise and the reference is a *permanent* constant -- baking a
#: single noisy frame into the catalog is exactly the kind of quiet, unfalsifiable error this
#: flow exists to end. Snapshots arrive every 200 ms, so this holds about six seconds.
#:
#: Each reading carries when it was taken. Without that the buffer answered "has this marker ever
#: been seen thirty times?" instead of "is this block sitting here now?", and the two diverge the
#: moment a block leaves the table -- see `building_registration.SIGHTING_WINDOW_SECONDS`.
REFERENCE_ROTATION_BUFFER = 30
recent_marker_rotations: dict[int, deque] = defaultdict(lambda: deque(maxlen=REFERENCE_ROTATION_BUFFER))

#: Where every marker was last seen in table pixels and when, catalogued or not: `(x, y, seen_at)`.
#:
#: `latest_table_pixel_positions` above deliberately holds only *catalogued* markers, because it
#: exists to file a calibration measurement against a known building. Registration needs the
#: opposite: the block it is about has no catalog entry yet, and the whole point is to find it by
#: where it is sitting.
#:
#: The timestamp is not decoration. This dict is never pruned, so without it a marker seen once,
#: minutes ago, stayed a live registration candidate at a pixel it had long since left.
latest_marker_pixels: dict[int, tuple[float, float, float]] = {}

# How stale a marker's last table-pixel reading may be before a measurement will not be filed
# against it. Snapshots arrive every 200 ms, so a couple of seconds is many frames of grace for a
# briefly occluded marker while still refusing a block that has left the table.
TABLE_POSITION_MAX_AGE_SECONDS = 3.0
# The calibration record (session_store.SessionStore). Lives next to server.py, not under
# logs/, because logs/ is gitignored throwaway output and this file is the measurements
# themselves -- the input to the global homography fit the next round derives.
SESSION_STORE_PATH = os.path.join(_SCRIPT_DIR, "calibration_sessions.sqlite3")
session_store = SessionStore(SESSION_STORE_PATH)
CALIBRATION_LOG_DIR = os.path.join(_SCRIPT_DIR, "logs", "calibration")
os.makedirs(CALIBRATION_LOG_DIR, exist_ok=True)
_calibration_log_path = os.path.join(
    CALIBRATION_LOG_DIR, f"calibration_{datetime.now():%Y%m%d_%H%M%S}.log"
)
calibration_logger = logging.getLogger("calibration")
calibration_logger.setLevel(logging.INFO)
calibration_logger.propagate = False  # never bleed into the root/console logging
if not calibration_logger.handlers:
    _calibration_handler = logging.FileHandler(_calibration_log_path, encoding="utf-8")
    _calibration_handler.setFormatter(logging.Formatter("%(asctime)s %(message)s"))
    calibration_logger.addHandler(_calibration_handler)


def markers_to_building_geojson(
    snapshot: dict, homography: BasemapHomography, scale: float = 1.0
) -> dict:
    """Resolve calibrated marker centres and emit catalog-owned building geometries."""
    marker_centres = markers_json_to_geojson(snapshot, homography)
    features = []
    for marker_feature in marker_centres["features"]:
        properties = marker_feature["properties"]
        marker_id = int(properties["marker_id"])
        building = physical_buildings_by_marker.get(marker_id)
        if building is None:
            if marker_id not in _warned_unknown_marker_ids:
                logging.getLogger(__name__).warning(
                    "Skipping marker %s because it is not in physical-building-catalog.json", marker_id
                )
                _warned_unknown_marker_ids.add(marker_id)
            continue
        center = tuple(marker_feature["geometry"]["coordinates"])
        table_pixel = (float(properties["table_x_px"]), float(properties["table_y_px"]))
        latest_table_pixel_positions[marker_id] = (*table_pixel, time.time())
        # D2: the marker's heading goes through the homography instead of being copied across
        # as a scalar. Bound to *this* marker's own table pixel, because the correction is
        # position-dependent -- the map is 3.5% anisotropic and 0.42 degrees out of square, so
        # the same block heading maps to different ground bearings in different corners of the
        # table. `building_feature` runs the stored reference through the same callable, which is
        # what keeps every already-registered `marker_reference_rotations` value valid.
        feature = building_feature(
            building,
            marker_id,
            center,
            float(properties["rotation"]),
            scale=scale,
            table_direction_to_map=partial(
                direction_through_homography, homography, table_pixel
            ),
        )
        # The panel's table diagram needs to know which regions of the table have been sampled,
        # and the calibration record needs where each measurement was taken; both read this.
        feature["properties"]["table_x_px"] = table_pixel[0]
        feature["properties"]["table_y_px"] = table_pixel[1]
        # The blocks' own scale, published so the panel can label an offset in table
        # millimetres without restating 1:500 on the frontend (OD: one source per number).
        feature["properties"]["model_scale"] = MODEL_SCALE
        # What this building's calibration currently *is*, in the units the panel nudges in, so
        # the panel opens showing where the building stands instead of at zero -- see
        # `calibration_as_message_fields`.
        feature["properties"]["calibration"] = calibration_as_message_fields(building)
        features.append(feature)
    return {"type": "FeatureCollection", "features": features}


def _remember_marker_rotations(snapshot: dict) -> None:
    """Keep each marker's recent headings, so a registration can average instead of sampling once.

    Fed from the raw snapshot rather than from `markers_to_building_geojson`, and that is the
    point: a building being registered for the first time is not in the catalog yet, so the
    geometry path skips its marker entirely. The one reading registration needs is the one the
    rest of the pipeline has no reason to keep.
    """
    for raw_marker_id, position in snapshot.items():
        try:
            marker_id = int(raw_marker_id)
            pixel_x, pixel_y = float(position[0]), float(position[1])
            rotation = float(position[2])
        except (TypeError, ValueError, IndexError):
            continue
        seen_at = time.time()
        recent_marker_rotations[marker_id].append((seen_at, rotation))
        latest_marker_pixels[marker_id] = (pixel_x, pixel_y, seen_at)


def _markers_on_table_message() -> dict:
    """Which markers the cameras can see right now, and which building each already speaks for.

    Published every cycle because the registration panel cannot derive it: the building feed
    carries only *catalogued* markers, so the one marker registration is actually about -- the
    unclaimed block in the operator's hand -- is precisely the one the frontend never hears
    about. Without this the operator has no way to name an id, and no way to tell an unseen
    block from a mis-aimed target.

    `building_id` is null for an unclaimed marker. A marker that already belongs to the building
    being registered is not excluded: re-registering is how a bad reference gets fixed.
    """
    on_table = markers_on_the_table(
        latest_marker_pixels,
        recent_marker_rotations,
        now=time.time(),
        reserved_ids=RESERVED_MARKER_IDS,
    )
    owners = physical_buildings_by_marker
    return {
        "type": "markers_on_table",
        "markers": [
            {
                "marker_id": marker_id,
                "building_id": (owners.get(marker_id) or {}).get("building_id"),
            }
            for marker_id in sorted(on_table)
        ],
    }


def _register_building(payload: dict, peer) -> dict:
    """Register the block on the table as `building_id`, or raise `ValueError` explaining why not.

    Called when the operator has turned the block parallel to its own footprint, projected on the
    table at the building's real heading. That confirmation is the whole measurement: at that
    instant the block's heading *is* the catalog's true-north heading, so the reference is right
    by construction and `rotation_offset_deg` is a measured zero rather than an unmeasured None
    (see `building_registration`).

    Writes the working catalog first and the live one from that same result, for the reason
    `_record_building_calibration` does: the two are only reconciled by a manual publish, so
    merging separately would draw one thing, persist another, and record a third.
    """
    global physical_building_catalog, physical_buildings_by_marker

    building_id = str(payload.get("building_id", "")).strip().upper()
    if not building_id:
        raise ValueError("no building_id in the message")

    with open(SOURCE_BUILDINGS_PATH, "r", encoding="utf-8") as source_file:
        source = json.load(source_file)
    matches = [
        feature
        for feature in source.get("features", [])
        if str(feature.get("properties", {}).get("building_id", "")).strip().upper() == building_id
    ]
    if not matches:
        raise ValueError(f"{building_id} is not in {os.path.basename(SOURCE_BUILDINGS_PATH)}")

    working_path = Path(WORKING_BUILDING_CATALOG_PATH)
    working_catalog = load_catalog(working_path)

    # What is on the table *now* -- not what has ever been seen. Both halves matter: enough
    # readings that a single noisy ArUco frame cannot pass as a block, and all of them recent
    # enough that they describe the table rather than the process's memory of it.
    now = time.time()
    steady = markers_on_the_table(
        latest_marker_pixels,
        recent_marker_rotations,
        now=now,
        reserved_ids=RESERVED_MARKER_IDS,
    )

    named = payload.get("marker_id")
    target = payload.get("target")
    if named is not None:
        # The operator naming the id outright. Deterministic, and the only path that does not
        # depend on the AOI-centre -> projector -> table -> camera -> pixel chain agreeing.
        try:
            named = int(named)
        except (TypeError, ValueError):
            raise ValueError(f"marker_id {named!r} is not a number") from None
        if named in RESERVED_MARKER_IDS:
            raise ValueError(f"marker {named} is a calibration marker and cannot be a building")
        marker_id = named_marker(working_catalog, building_id, named, steady)
    elif target is not None and basemap_homography is not None:
        # The operator has already answered "which block is this?" physically, by putting it on
        # the projected target. Reading it off position is what makes every other object on the
        # table irrelevant, rather than a reason to refuse.
        easting, northing = _WGS84_TO_UTM.transform(float(target[0]), float(target[1]))
        (target_pixel,) = project_utm_to_pixels(
            basemap_homography, np.array([[easting, northing]], dtype=np.float64)
        )
        # The refusal below is the only window onto why a registration failed, and on the
        # 2026-09-04 rig it was too narrow to diagnose anything. Record what the server was
        # actually looking at, so one attempt at the table settles it.
        calibration_logger.info(
            "REGISTRATION SIGHTING from %s | building=%s | target_lnglat=%s | "
            "target_pixel=(%.1f, %.1f) | on_table=%s | seen_but_stale=%s",
            peer,
            building_id,
            list(target),
            float(target_pixel[0]),
            float(target_pixel[1]),
            {mid: (round(x, 1), round(y, 1)) for mid, (x, y) in sorted(steady.items())},
            sorted(set(latest_marker_pixels) - set(steady) - RESERVED_MARKER_IDS),
        )
        marker_id = marker_on_target(steady, (float(target_pixel[0]), float(target_pixel[1])))
    else:
        marker_id = marker_to_register(
            working_catalog, building_id, sorted(steady), RESERVED_MARKER_IDS
        )
    reference_rotation = reference_rotation_from_samples(
        recent_rotations(recent_marker_rotations[marker_id], now=now)
    )

    entry = registered_entry(matches[0], marker_id, reference_rotation)
    save_catalog(working_path, catalog_with_entry(working_catalog, entry))

    # The live catalog takes that same result, so what the operator sees on the table and what is
    # on disk are the same thing by construction rather than by two matching merges.
    physical_building_catalog = catalog_with_entry(physical_building_catalog, entry)
    physical_buildings_by_marker = marker_index(physical_building_catalog)
    _warned_unknown_marker_ids.discard(marker_id)

    calibration_logger.info(
        "BUILDING REGISTERED from %s | building=%s | marker=%s | reference_rotation=%.4f "
        "| samples=%s | working_catalog=%s",
        peer,
        building_id,
        marker_id,
        reference_rotation,
        len(recent_marker_rotations[marker_id]),
        working_path,
    )
    return {
        "type": "register_building_result",
        "ok": True,
        "building_id": building_id,
        "marker_id": marker_id,
        "reference_rotation_deg": reference_rotation,
        "sample_count": len(recent_marker_rotations[marker_id]),
    }


def _record_building_calibration(payload: dict, peer) -> None:
    """Apply one `building_calibration` message, or raise `ValueError` explaining why not.

    Refusals are all the same shape: the message describes a *residual*, and a residual that
    cannot be tied to both a global mapping (the session) and a place on the table is not a
    measurement -- storing it would pollute the very dataset the global fit is derived from.
    """
    global physical_building_catalog, physical_buildings_by_marker

    if current_session_id is None:
        raise ValueError("no calibration in force; send map_calibration first")

    try:
        marker_id = int(payload["marker_id"])
        building_id = str(payload["building_id"]).strip().upper()
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(f"missing or unreadable marker_id/building_id: {exc}") from None

    building = physical_buildings_by_marker.get(marker_id)
    if building is None:
        raise ValueError(f"marker {marker_id} is not in the physical building catalog")
    if building["building_id"] != building_id:
        raise ValueError(
            f"marker {marker_id} belongs to {building['building_id']}, not {building_id}; "
            "the panel and the catalog disagree about what was moved"
        )

    reading = latest_table_pixel_positions.get(marker_id)
    if reading is None:
        raise ValueError(
            f"marker {marker_id} has not been seen on the table yet, so there is no position "
            "to record the measurement at"
        )
    table_x_px, table_y_px, seen_at = reading
    age_seconds = time.time() - seen_at
    if age_seconds > TABLE_POSITION_MAX_AGE_SECONDS:
        raise ValueError(
            f"marker {marker_id} was last seen {age_seconds:.1f}s ago; a measurement filed at a "
            "position the block is no longer at would corrupt the position-dependent signal the "
            "record exists for"
        )
    table_pixel = (table_x_px, table_y_px)

    unknown = sorted(
        set(payload)
        - set(BUILDING_CALIBRATION_MESSAGE_FIELDS)
        - {"type", "version", "building_id", "marker_id"}
    )
    if unknown:
        raise ValueError(f"unknown field(s) {', '.join(unknown)}")
    calibration = calibration_from_message(payload)
    if not calibration:
        raise ValueError("message carries no calibration field to apply")

    # The working catalog on disk is the one that persists; write it first, so a failure there
    # cannot leave the live catalog ahead of the file the next boot reads.
    working_path = Path(WORKING_BUILDING_CATALOG_PATH)
    working_catalog = load_catalog(working_path)
    working_index = {
        entry["building_id"]: index for index, entry in enumerate(working_catalog["buildings"])
    }
    if building_id not in working_index:
        raise ValueError(f"{building_id} is not in the working catalog at {working_path}")
    position = working_index[building_id]
    updated_entry = apply_building_calibration(
        working_catalog["buildings"][position], calibration
    )
    working_catalog["buildings"][position] = updated_entry
    save_catalog(working_path, working_catalog)
    stored = updated_entry["calibration"]

    # The live catalog then takes that same *result*, not a second merge of its own. The two
    # catalogs are only reconciled by a manual publish-to-runtime.ps1, so they can legitimately
    # start from different values -- and merging one partial message onto two different bases
    # would draw one thing on the table, persist another, and record a third. Copying the result
    # makes what the operator sees and what is stored the same by construction.
    updated_runtime = copy.deepcopy(physical_building_catalog)
    for index, entry in enumerate(updated_runtime["buildings"]):
        if entry["building_id"] == building_id:
            updated_runtime["buildings"][index] = {
                **entry,
                "calibration": copy.deepcopy(stored),
            }
            break
    physical_building_catalog = updated_runtime
    physical_buildings_by_marker = marker_index(physical_building_catalog)
    session_store.record_building(
        current_session_id,
        BuildingCalibration(
            building_id=building_id,
            marker_id=marker_id,
            rotation_offset_deg=stored["rotation_offset_deg"],
            offset_east_m=stored["offset_east_m"],
            offset_north_m=stored["offset_north_m"],
            scale_residual=stored["scale_residual"],
            table_x_px=table_pixel[0],
            table_y_px=table_pixel[1],
        ),
    )
    calibration_logger.info(
        "BUILDING CALIBRATION ACCEPTED from %s | session=%s | building=%s | marker=%s "
        "| applied=%s | stored=%s | table_px=%s | working_catalog=%s",
        peer,
        current_session_id,
        building_id,
        marker_id,
        json.dumps(calibration),
        json.dumps(stored),
        table_pixel,
        working_path,
    )


def _parse_calibration_points(raw_points: list) -> list[BasemapCalibrationPoint]:
    return [
        BasemapCalibrationPoint(
            pixel_position=tuple(point["pixel_position"]),
            lat_lon_position=tuple(point["lat_lon_position"]),
        )
        for point in raw_points
    ]


def _detection_worker(interval_ns: int = 200_000_000):
    """Runs on a dedicated background thread (NOT the asyncio event loop).

    Continuously captures/stitches/detects camera frames (all blocking,
    CPU/hardware-bound work) and pushes an accumulated marker snapshot onto
    `tracking_queue` every `interval_ns`. Keeping this off the event loop
    thread means network I/O (receiving/sending on sockets/websockets) is
    never blocked by camera polling or cv2 rendering.
    """
    markers_holder = Markers()
    last_sent = time_ns()

    for stitched_image in process_and_join_streams(stitching_setup):
        corners, ids, rejectedImgPoints = detect_markers(stitched_image)  # runs detection.
        buildingDict = map_detected_markers("000", ids, corners)

        draw_monitor_window(stitched_image, corners, rejectedImgPoints, "000")
        draw_status_window(buildingDict, "000")

        markers_holder.addMarkers(list(buildingDict.values()))

        if (time_ns() - last_sent > interval_ns):
            snapshot = markers_holder.toDict()

            # Keep only the freshest snapshot if the consumer is falling behind.
            if tracking_queue.full():
                try:
                    tracking_queue.get_nowait()
                except queue_module.Empty:
                    pass
            tracking_queue.put_nowait(snapshot)

            last_sent = time_ns()
            markers_holder.clear()


def start_detection_thread():
    threading.Thread(target=_detection_worker, name="detection-worker", daemon=True).start()


async def stream_tracking_updates(send):
    """Consume marker snapshots from `tracking_queue` and forward each via `send`.

    `send` is an async callable taking a marker snapshot dict; it should
    format and transmit it to the client.
    """
    while True:
        snapshot = await asyncio.to_thread(tracking_queue.get)
        await send(snapshot)


async def handle_web_client(websocket):
    """Handle a web client websocket connection: receive calibration updates
    and stream tracking results back.

    Expected incoming message schema:
        {"type": "map_calibration", "points": [{"pixel_position": [x, y], "utm_position": [x, y]}, ...]}
        {"type": "clear_calibration"}  # drops the current homography; resumes raw marker output
        {"type": "register_building", "building_id": "G11", "target": [lng, lat]}
         # Sent when the operator has turned the block PARALLEL to its own footprint, which the
         # frontend projects on the table at the building's real heading. Carries no marker id:
         # a building being registered for the first time has no catalog entry, so there is none
         # to send -- the server resolves it as the one marker on the table no building claims.
         # Parallel, not on top of: the reference needs only the angle, so the block may sit
         # anywhere, which is what lets an operator check both cameras across the table.
        {"type": "building_calibration", "building_id": "G07", "marker_id": 12,
         # `rotation_offset_deg` is nullable in BOTH directions: Python publishes `null` for a
         # building whose heading has never been verified, and accepts `null` to put one back to
         # unverified. A panel that does arithmetic on it without a null check will either throw
         # or coerce to 0 -- which reinstates the measured-zero conflation this exists to end.
         "rotation_offset_deg": ...,  # float | null
         "offset_east_mm": ..., "offset_north_mm": ...,
         "scale_residual": ...}  # any subset of the four; merged onto what is stored.
        # Offsets are table millimetres in the building's own local frame; the catalog stores
        # them as real metres (physical_building_catalog.calibration_from_message).

    Outgoing tracking messages are sent as GeoJSON once a basemap homography
    is available (i.e. after a map_calibration message has been received),
    otherwise as a plain dict of markers. A "clear_calibration" message reverts
    to the plain-dict output until the next "map_calibration" is received.
    """
    peer = websocket.remote_address
    print(f"Web client connected: {peer}")

    async def receive_messages():
        global basemap_homography, global_model_scale_factor, current_session_id
        async for message in websocket:
            try:
                payload = json.loads(message)
            except json.JSONDecodeError:
                print(f"Could not parse message from web client: {message!r}")
                continue

            message_type = payload.get("type")

            if message_type == "map_calibration":
                try:
                    calibration_points = _parse_calibration_points(payload["points"])
                    basemap_homography = create_basemap_homography(calibration_points)
                    table_ground_scale = ground_scale(basemap_homography)
                    global_model_scale_factor = model_scale_factor(table_ground_scale)
                    # The four accepted `lat_lon_position`s *are* this AOI's signature -- they
                    # are the AOI's own inset corners, and they are the only geographic thing
                    # the handshake carries -- so they stand in for the AOI corners the session
                    # id hashes. Same AOI, same id; a different AOI can never collide with it.
                    current_session_id = session_store.begin_session(
                        aoi_corners=[list(p.lat_lon_position) for p in calibration_points],
                        ground_scale=table_ground_scale,
                        homography=basemap_homography.matrix.tolist(),
                        global_k=global_model_scale_factor,
                    )
                    print(
                        f"Updated basemap homography from {len(calibration_points)} calibration points "
                        f"(1:{table_ground_scale:.1f} map, catalog geometry scaled by "
                        f"{global_model_scale_factor:.4f}, session {current_session_id})"
                    )
                    # The frontend needs this to draw a registration target at the size of the
                    # physical block. It already receives `model_scale_factor` on every tracked
                    # building, but a building being registered for the first time has no feature
                    # yet -- which is precisely when the number is needed.
                    await websocket.send(
                        json.dumps(
                            {
                                "type": "session_state",
                                "session_id": current_session_id,
                                "model_scale": MODEL_SCALE,
                                "model_scale_factor": global_model_scale_factor,
                                "ground_scale": table_ground_scale,
                            }
                        )
                    )
                    calibration_logger.info(
                        "CALIBRATION UPDATED from %s | session=%s | ground_scale=%.4f "
                        "| model_scale_factor=%.6f | points=%s | homography_matrix=%s | utm_offset=%s",
                        peer,
                        current_session_id,
                        table_ground_scale,
                        global_model_scale_factor,
                        json.dumps(
                            [
                                {
                                    "pixel_position": p.pixel_position,
                                    "lat_lon_position": p.lat_lon_position,
                                    "utm_position": p.utm_position,
                                }
                                for p in calibration_points
                            ]
                        ),
                        basemap_homography.matrix.tolist(),
                        basemap_homography.utm_offset,
                    )
                except (KeyError, ValueError) as exc:
                    print(f"Invalid map_calibration payload: {exc}")
                    calibration_logger.info(
                        "CALIBRATION REJECTED from %s | error=%s | raw_payload=%s",
                        peer,
                        exc,
                        payload,
                    )

            elif message_type == "clear_calibration":
                basemap_homography = None
                global_model_scale_factor = None
                current_session_id = None
                # Table positions belong to the calibration that produced them: a pixel read under
                # the old homography says nothing about where a block sits under the next one.
                latest_table_pixel_positions.clear()
                print("Cleared basemap homography; resuming raw marker output")
                calibration_logger.info("CALIBRATION CLEARED from %s", peer)

            elif message_type == "building_calibration":
                try:
                    _record_building_calibration(payload, peer)
                    print(
                        "Applied building_calibration for "
                        f"{payload.get('building_id')} (marker {payload.get('marker_id')}); run "
                        "building_catalog/publish-to-runtime.ps1 to make it the next boot default"
                    )
                except (KeyError, TypeError, ValueError) as exc:
                    # Never let a bad message close the socket: a dropped connection ends the
                    # operator's calibration session, which costs far more than a rejected nudge.
                    print(f"Rejected building_calibration: {exc}")
                    calibration_logger.info(
                        "BUILDING CALIBRATION REJECTED from %s | error=%s | raw_payload=%s",
                        peer,
                        exc,
                        payload,
                    )

            elif message_type == "register_building":
                try:
                    result = _register_building(payload, peer)
                    print(
                        f"Registered {result['building_id']} -> marker {result['marker_id']} at "
                        f"reference rotation {result['reference_rotation_deg']:.3f} deg; run "
                        "building_catalog/publish-to-runtime.ps1 to make it the next boot default"
                    )
                    await websocket.send(json.dumps(result))
                except (KeyError, OSError, TypeError, ValueError) as exc:
                    print(f"Rejected register_building: {exc}")
                    calibration_logger.info(
                        "BUILDING REGISTRATION REJECTED from %s | error=%s | raw_payload=%s",
                        peer,
                        exc,
                        payload,
                    )
                    await websocket.send(
                        json.dumps(
                            {
                                "type": "register_building_result",
                                "ok": False,
                                "building_id": payload.get("building_id"),
                                "error": str(exc),
                            }
                        )
                    )

            else:
                print(f"Unknown message type from web client: {message_type!r}")

    async def send_tracking_updates():
        async def send(snapshot: dict):
            global basemap_homography

            _remember_marker_rotations(snapshot)

            # Once the web client has sent map calibration points, convert
            # marker positions to GeoJSON; until then, send a plain dict
            # of markers.
            if basemap_homography is not None:
                markers_json = json.dumps(
                    markers_to_building_geojson(
                        snapshot, basemap_homography, scale=global_model_scale_factor or 1.0
                    )
                )
            else:
                markers_json = json.dumps(snapshot)

            print("Sending to web client:", markers_json)
            await websocket.send(markers_json)
            await websocket.send(json.dumps(_markers_on_table_message()))

        await stream_tracking_updates(send)  # 200ms interval between updates

    try:
        await asyncio.gather(receive_messages(), send_tracking_updates())
    except websockets.exceptions.ConnectionClosed as exc:
        print(f"Web client connection closed: {exc}")
    except Exception:
        print(f"Web client handler crashed for {peer}:")
        import traceback
        traceback.print_exc()
    finally:
        print(f"Web client disconnected: {peer}")


async def run_web_server():
    async with websockets.serve(handle_web_client, WEB_WS_HOST, WEB_WS_PORT):
        print(f"Listening for web client connections on {WEB_WS_HOST}:{WEB_WS_PORT}")
        await asyncio.Future()  # run forever


def setup_pixel_socket():
    global pixel_socket
    pixel_socket = socket_module.socket(socket_module.AF_INET, socket_module.SOCK_STREAM)
    print(f"Listening to socket connections on: {PIXEL_SOCKET_SETTINGS}")
    pixel_socket.bind(PIXEL_SOCKET_SETTINGS)
    pixel_socket.listen(1)
    pixel_socket.setblocking(False)


async def run_pixel_socket_server():
    while True:
        connection, client_address = await loop.sock_accept(pixel_socket)
        print(f"Unity client connected from: {client_address}")
        loop.create_task(send_tracking_matches_unity(connection))


async def send_tracking_matches_unity(connection):
    """Stream marker JSON to a Unity client.

    Always sends the raw marker JSON string, regardless of whether a basemap
    homography has been configured; the Unity client does not send anything
    back to the server.

    The third element of each marker tuple is `detection.normalizeCorners`'s raw table-frame
    angle, and it CHANGED SIGN on 2026-09-04 when the stray `-1` came out of that function. This
    path applies no correction of its own -- deliberately: the raw stream is raw, and the
    homography-aware heading (`markers_to_building_geojson`) only exists once a `map_calibration`
    has arrived, which a Unity client never sends. So a Unity consumer that rotates its models by
    `snapshot[id][2]` now turns them the other way than it did before that commit. The same is
    true of the web client's pre-calibration frames below. Neither consumer lives in this repo,
    so nothing here can test it; it is called out so the next person to see models spinning
    backwards finds the reason in one place instead of re-deriving it.
    """
    async def send(snapshot: dict):
        markers_json = json.dumps(snapshot)
        print("Sending to Unity client:", markers_json)
        await loop.sock_sendall(connection, markers_json.encode("utf-8"))

    await stream_tracking_updates(send)


async def main(client: str, calibrate: bool = False):
    # Legacy calibration/camera helpers still use relative paths. Always resolve
    # them from the project directory so terminal and IDE launches behave alike.
    os.chdir(_SCRIPT_DIR)
    print(
        f"Loaded {len(physical_building_catalog['buildings'])} physical buildings "
        f"from {PHYSICAL_BUILDING_CATALOG_PATH}"
    )
    calibration_path = Path(_SCRIPT_DIR) / "calibration_markers.json"
    if calibrate:
        print("Calibration mode requested; rebuilding camera calibration...")
        calibration_data = calibrate_fixed_rig(calibration_path)
    else:
        print(f"Loading existing camera calibration from {calibration_path}")
        calibration_data = load_calibration_markers(str(calibration_path))

    # Initialize camera stitching from the selected calibration data.
    global stitching_setup
    stitching_setup = setup_camera_transforms(calibration_data)

    # Detection/stitching runs on its own thread so it never blocks the
    # asyncio event loop (which handles client I/O).
    start_detection_thread()

    print(f"waiting for {client} client to connect")

    if client == "unity":
        setup_pixel_socket()
        await run_pixel_socket_server()
    else:
        await run_web_server()


def shutdown_handler(sig, frame):
    """Handle graceful shutdown"""
    print("\nShutting down server...")
    if pixel_socket is not None:
        print("Closing socket...")
        pixel_socket.close()
    print("Stopping event loop...")
    loop.stop()
    sys.exit(0)


def parse_args():
    parser = argparse.ArgumentParser(description="COUP table object tracking server")
    parser.add_argument(
        "--client",
        choices=["unity", "web"],
        default="web",
        required=False,
        help="Which client to serve: 'unity' (raw TCP socket, marker JSON) or 'web' (websocket, geojson/dict)",
    )
    parser.add_argument(
        "--calibrate",
        action="store_true",
        help="Run the fixed-rig camera calibration before starting tracking",
    )
    return parser.parse_args()


def run_from_command_line():
    args = parse_args()

    logging.basicConfig(level=logging.INFO)

    # Register signal handlers
    signal.signal(signal.SIGINT, shutdown_handler)  # Ctrl+C
    signal.signal(signal.SIGTERM, shutdown_handler)  # Termination signal

    try:
        loop.run_until_complete(main(args.client, calibrate=args.calibrate))
    except KeyboardInterrupt:
        shutdown_handler(None, None)
    finally:
        if pixel_socket is not None:
            pixel_socket.close()
        loop.close()


# Guarded so the module can be imported (by tests, and by anything that wants
# `handle_web_client` without owning the process). `python server.py` is unchanged:
# argument parsing, signal handlers and the event loop all still run exactly as before.
if __name__ == "__main__":
    run_from_command_line()
