import argparse
import asyncio
import copy
import json
import logging
import os
import queue as queue_module
import socket as socket_module
import signal
import sys
import threading
import time
from datetime import datetime
from functools import partial
from pathlib import Path

from marker import Markers, map_detected_markers
from time import time_ns
from detection import detect_markers
from hud import draw_monitor_window, draw_status_window
from automatic_calibration import calibrate_fixed_rig
from calibration_handler import load_calibration_markers
from camera_stitching import setup_camera_transforms, process_and_join_streams
from pixel_to_utm import (
    BasemapCalibrationPoint,
    BasemapHomography,
    create_basemap_homography,
    direction_through_homography,
    ground_scale,
)
from table_to_geojson import markers_json_to_geojson
from physical_building_catalog import (
    BUILDING_CALIBRATION_MESSAGE_FIELDS,
    MODEL_SCALE,
    apply_building_calibration,
    calibration_as_message_fields,
    calibration_from_message,
    building_feature,
    load_catalog,
    marker_index,
    model_scale_factor,
    save_catalog,
)
from session_store import BuildingCalibration, SessionStore
import websockets

# Windows consoles default to a non-UTF-8 codepage (e.g. cp1252), which
# crashes on the emoji used throughout this codebase's print() calls.
sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

# Global variable for stitching setup
stitching_setup = None

# Basemap homography computed from the web client's map_calibration message.
# None until the web client sends calibration points, in which case tracking
# matches are sent as GeoJSON (see handle_web_client); otherwise a plain
# marker dict is sent.
basemap_homography: BasemapHomography | None = None

# How far catalog geometry must shrink to sit on top of its 1:500 block under the *current*
# calibration (physical_building_catalog.model_scale_factor). Derived from the homography the
# moment one is accepted -- never sent by the frontend, never measured by hand -- and reset to
# None alongside it, so a stale factor can never outlive the calibration it was derived from.
global_model_scale_factor: float | None = None

# The session_store id of the calibration currently in force. Generated by Python from the
# accepted handshake (the frontend has no session id and sends none), so every building
# measurement can be filed against the homography it was actually measured under.
current_session_id: str | None = None

# Raw TCP socket used only for the "unity" client. Created in setup_pixel_socket().
pixel_socket = None
PIXEL_SOCKET_SETTINGS = ("localhost", 8052)

loop = asyncio.new_event_loop()

WEB_WS_HOST = "0.0.0.0"
WEB_WS_PORT = 8053

# Marker snapshots (dicts) produced by the detection thread, consumed by
# whichever client (unity/web) is sending tracking updates. Bounded to 1 so
# stale snapshots get replaced instead of piling up if a consumer falls behind.
tracking_queue: "queue_module.Queue[dict]" = queue_module.Queue(maxsize=1)

# Dedicated calibration log: every accepted/rejected map_calibration message gets its own
# timestamped line here, separate from the console (which is too noisy from the detection
# loop to spot a calibration change in). One file per server run under logs/calibration/.
# Anchored to this script's own directory (not the process's cwd) so the folder always
# lands next to server.py regardless of where the server is launched from.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PHYSICAL_BUILDING_CATALOG_PATH = os.path.join(_SCRIPT_DIR, "physical-building-catalog.json")

# Where an accepted `building_calibration` is written. Deliberately *not* the runtime catalog
# above: `building_catalog/publish-to-runtime.ps1` promotes this file to that one, so an operator
# saving a value mid-session cannot corrupt the catalog the running server booted from. The
# in-memory catalog is updated too, so the nudge is visible on the projection immediately -- it
# just does not become the next boot's default until someone publishes it.
WORKING_BUILDING_CATALOG_PATH = os.path.join(
    _SCRIPT_DIR, "building_catalog", "physical-building-catalog.json"
)
physical_building_catalog = load_catalog(Path(PHYSICAL_BUILDING_CATALOG_PATH))
physical_buildings_by_marker = marker_index(physical_building_catalog)
_warned_unknown_marker_ids: set[int] = set()

# Where each building marker was last seen in table-pixel space, and when. Python owns pixel
# space -- once a homography exists the frontend only ever sees WGS84 -- so the server stamps
# every recorded measurement with its own latest reading rather than trusting a value echoed
# back to it.
#
# The timestamp is not bookkeeping: `table_x_px`/`table_y_px` exist to tell a position-dependent
# homography error apart from a per-building one, so a measurement filed at a position the block
# was not actually at corrupts the exact signal the whole record is kept for. A marker that has
# stopped being seen keeps its last reading here forever otherwise, and a building left in
# `session.tracking` could be saved against a position from a previous sitting.
latest_table_pixel_positions: dict[int, tuple[float, float, float]] = {}

# How stale a marker's last table-pixel reading may be before a measurement will not be filed
# against it. Snapshots arrive every 200 ms, so a couple of seconds is many frames of grace for a
# briefly occluded marker while still refusing a block that has left the table.
TABLE_POSITION_MAX_AGE_SECONDS = 3.0
# The calibration record (session_store.SessionStore). Lives next to server.py, not under
# logs/, because logs/ is gitignored throwaway output and this file is the measurements
# themselves -- the input to the global homography fit the next round derives.
SESSION_STORE_PATH = os.path.join(_SCRIPT_DIR, "calibration_sessions.sqlite3")
session_store = SessionStore(SESSION_STORE_PATH)
CALIBRATION_LOG_DIR = os.path.join(_SCRIPT_DIR, "logs", "calibration")
os.makedirs(CALIBRATION_LOG_DIR, exist_ok=True)
_calibration_log_path = os.path.join(
    CALIBRATION_LOG_DIR, f"calibration_{datetime.now():%Y%m%d_%H%M%S}.log"
)
calibration_logger = logging.getLogger("calibration")
calibration_logger.setLevel(logging.INFO)
calibration_logger.propagate = False  # never bleed into the root/console logging
if not calibration_logger.handlers:
    _calibration_handler = logging.FileHandler(_calibration_log_path, encoding="utf-8")
    _calibration_handler.setFormatter(logging.Formatter("%(asctime)s %(message)s"))
    calibration_logger.addHandler(_calibration_handler)


def markers_to_building_geojson(
    snapshot: dict, homography: BasemapHomography, scale: float = 1.0
) -> dict:
    """Resolve calibrated marker centres and emit catalog-owned building geometries."""
    marker_centres = markers_json_to_geojson(snapshot, homography)
    features = []
    for marker_feature in marker_centres["features"]:
        properties = marker_feature["properties"]
        marker_id = int(properties["marker_id"])
        building = physical_buildings_by_marker.get(marker_id)
        if building is None:
            if marker_id not in _warned_unknown_marker_ids:
                logging.getLogger(__name__).warning(
                    "Skipping marker %s because it is not in physical-building-catalog.json", marker_id
                )
                _warned_unknown_marker_ids.add(marker_id)
            continue
        center = tuple(marker_feature["geometry"]["coordinates"])
        table_pixel = (float(properties["table_x_px"]), float(properties["table_y_px"]))
        latest_table_pixel_positions[marker_id] = (*table_pixel, time.time())
        # D2: the marker's heading goes through the homography instead of being copied across
        # as a scalar. Bound to *this* marker's own table pixel, because the correction is
        # position-dependent -- the map is 3.5% anisotropic and 0.42 degrees out of square, so
        # the same block heading maps to different ground bearings in different corners of the
        # table. `building_feature` runs the stored reference through the same callable, which is
        # what keeps every already-registered `marker_reference_rotations` value valid.
        feature = building_feature(
            building,
            marker_id,
            center,
            float(properties["rotation"]),
            scale=scale,
            table_direction_to_map=partial(
                direction_through_homography, homography, table_pixel
            ),
        )
        # The panel's table diagram needs to know which regions of the table have been sampled,
        # and the calibration record needs where each measurement was taken; both read this.
        feature["properties"]["table_x_px"] = table_pixel[0]
        feature["properties"]["table_y_px"] = table_pixel[1]
        # The blocks' own scale, published so the panel can label an offset in table
        # millimetres without restating 1:500 on the frontend (OD: one source per number).
        feature["properties"]["model_scale"] = MODEL_SCALE
        # What this building's calibration currently *is*, in the units the panel nudges in, so
        # the panel opens showing where the building stands instead of at zero -- see
        # `calibration_as_message_fields`.
        feature["properties"]["calibration"] = calibration_as_message_fields(building)
        features.append(feature)
    return {"type": "FeatureCollection", "features": features}


def _record_building_calibration(payload: dict, peer) -> None:
    """Apply one `building_calibration` message, or raise `ValueError` explaining why not.

    Refusals are all the same shape: the message describes a *residual*, and a residual that
    cannot be tied to both a global mapping (the session) and a place on the table is not a
    measurement -- storing it would pollute the very dataset the global fit is derived from.
    """
    global physical_building_catalog, physical_buildings_by_marker

    if current_session_id is None:
        raise ValueError("no calibration in force; send map_calibration first")

    try:
        marker_id = int(payload["marker_id"])
        building_id = str(payload["building_id"]).strip().upper()
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(f"missing or unreadable marker_id/building_id: {exc}") from None

    building = physical_buildings_by_marker.get(marker_id)
    if building is None:
        raise ValueError(f"marker {marker_id} is not in the physical building catalog")
    if building["building_id"] != building_id:
        raise ValueError(
            f"marker {marker_id} belongs to {building['building_id']}, not {building_id}; "
            "the panel and the catalog disagree about what was moved"
        )

    reading = latest_table_pixel_positions.get(marker_id)
    if reading is None:
        raise ValueError(
            f"marker {marker_id} has not been seen on the table yet, so there is no position "
            "to record the measurement at"
        )
    table_x_px, table_y_px, seen_at = reading
    age_seconds = time.time() - seen_at
    if age_seconds > TABLE_POSITION_MAX_AGE_SECONDS:
        raise ValueError(
            f"marker {marker_id} was last seen {age_seconds:.1f}s ago; a measurement filed at a "
            "position the block is no longer at would corrupt the position-dependent signal the "
            "record exists for"
        )
    table_pixel = (table_x_px, table_y_px)

    unknown = sorted(
        set(payload)
        - set(BUILDING_CALIBRATION_MESSAGE_FIELDS)
        - {"type", "version", "building_id", "marker_id"}
    )
    if unknown:
        raise ValueError(f"unknown field(s) {', '.join(unknown)}")
    calibration = calibration_from_message(payload)
    if not calibration:
        raise ValueError("message carries no calibration field to apply")

    # The working catalog on disk is the one that persists; write it first, so a failure there
    # cannot leave the live catalog ahead of the file the next boot reads.
    working_path = Path(WORKING_BUILDING_CATALOG_PATH)
    working_catalog = load_catalog(working_path)
    working_index = {
        entry["building_id"]: index for index, entry in enumerate(working_catalog["buildings"])
    }
    if building_id not in working_index:
        raise ValueError(f"{building_id} is not in the working catalog at {working_path}")
    position = working_index[building_id]
    updated_entry = apply_building_calibration(
        working_catalog["buildings"][position], calibration
    )
    working_catalog["buildings"][position] = updated_entry
    save_catalog(working_path, working_catalog)
    stored = updated_entry["calibration"]

    # The live catalog then takes that same *result*, not a second merge of its own. The two
    # catalogs are only reconciled by a manual publish-to-runtime.ps1, so they can legitimately
    # start from different values -- and merging one partial message onto two different bases
    # would draw one thing on the table, persist another, and record a third. Copying the result
    # makes what the operator sees and what is stored the same by construction.
    updated_runtime = copy.deepcopy(physical_building_catalog)
    for index, entry in enumerate(updated_runtime["buildings"]):
        if entry["building_id"] == building_id:
            updated_runtime["buildings"][index] = {
                **entry,
                "calibration": copy.deepcopy(stored),
            }
            break
    physical_building_catalog = updated_runtime
    physical_buildings_by_marker = marker_index(physical_building_catalog)
    session_store.record_building(
        current_session_id,
        BuildingCalibration(
            building_id=building_id,
            marker_id=marker_id,
            rotation_offset_deg=stored["rotation_offset_deg"],
            offset_east_m=stored["offset_east_m"],
            offset_north_m=stored["offset_north_m"],
            scale_residual=stored["scale_residual"],
            table_x_px=table_pixel[0],
            table_y_px=table_pixel[1],
        ),
    )
    calibration_logger.info(
        "BUILDING CALIBRATION ACCEPTED from %s | session=%s | building=%s | marker=%s "
        "| applied=%s | stored=%s | table_px=%s | working_catalog=%s",
        peer,
        current_session_id,
        building_id,
        marker_id,
        json.dumps(calibration),
        json.dumps(stored),
        table_pixel,
        working_path,
    )


def _parse_calibration_points(raw_points: list) -> list[BasemapCalibrationPoint]:
    return [
        BasemapCalibrationPoint(
            pixel_position=tuple(point["pixel_position"]),
            lat_lon_position=tuple(point["lat_lon_position"]),
        )
        for point in raw_points
    ]


def _detection_worker(interval_ns: int = 200_000_000):
    """Runs on a dedicated background thread (NOT the asyncio event loop).

    Continuously captures/stitches/detects camera frames (all blocking,
    CPU/hardware-bound work) and pushes an accumulated marker snapshot onto
    `tracking_queue` every `interval_ns`. Keeping this off the event loop
    thread means network I/O (receiving/sending on sockets/websockets) is
    never blocked by camera polling or cv2 rendering.
    """
    markers_holder = Markers()
    last_sent = time_ns()

    for stitched_image in process_and_join_streams(stitching_setup):
        corners, ids, rejectedImgPoints = detect_markers(stitched_image)  # runs detection.
        buildingDict = map_detected_markers("000", ids, corners)

        draw_monitor_window(stitched_image, corners, rejectedImgPoints, "000")
        draw_status_window(buildingDict, "000")

        markers_holder.addMarkers(list(buildingDict.values()))

        if (time_ns() - last_sent > interval_ns):
            snapshot = markers_holder.toDict()

            # Keep only the freshest snapshot if the consumer is falling behind.
            if tracking_queue.full():
                try:
                    tracking_queue.get_nowait()
                except queue_module.Empty:
                    pass
            tracking_queue.put_nowait(snapshot)

            last_sent = time_ns()
            markers_holder.clear()


def start_detection_thread():
    threading.Thread(target=_detection_worker, name="detection-worker", daemon=True).start()


async def stream_tracking_updates(send):
    """Consume marker snapshots from `tracking_queue` and forward each via `send`.

    `send` is an async callable taking a marker snapshot dict; it should
    format and transmit it to the client.
    """
    while True:
        snapshot = await asyncio.to_thread(tracking_queue.get)
        await send(snapshot)


async def handle_web_client(websocket):
    """Handle a web client websocket connection: receive calibration updates
    and stream tracking results back.

    Expected incoming message schema:
        {"type": "map_calibration", "points": [{"pixel_position": [x, y], "utm_position": [x, y]}, ...]}
        {"type": "clear_calibration"}  # drops the current homography; resumes raw marker output
        {"type": "building_calibration", "building_id": "G07", "marker_id": 12,
         "rotation_offset_deg": ..., "offset_east_mm": ..., "offset_north_mm": ...,
         "scale_residual": ...}  # any subset of the four; merged onto what is stored.
        # Offsets are table millimetres in the building's own local frame; the catalog stores
        # them as real metres (physical_building_catalog.calibration_from_message).

    Outgoing tracking messages are sent as GeoJSON once a basemap homography
    is available (i.e. after a map_calibration message has been received),
    otherwise as a plain dict of markers. A "clear_calibration" message reverts
    to the plain-dict output until the next "map_calibration" is received.
    """
    peer = websocket.remote_address
    print(f"Web client connected: {peer}")

    async def receive_messages():
        global basemap_homography, global_model_scale_factor, current_session_id
        async for message in websocket:
            try:
                payload = json.loads(message)
            except json.JSONDecodeError:
                print(f"Could not parse message from web client: {message!r}")
                continue

            message_type = payload.get("type")

            if message_type == "map_calibration":
                try:
                    calibration_points = _parse_calibration_points(payload["points"])
                    basemap_homography = create_basemap_homography(calibration_points)
                    table_ground_scale = ground_scale(basemap_homography)
                    global_model_scale_factor = model_scale_factor(table_ground_scale)
                    # The four accepted `lat_lon_position`s *are* this AOI's signature -- they
                    # are the AOI's own inset corners, and they are the only geographic thing
                    # the handshake carries -- so they stand in for the AOI corners the session
                    # id hashes. Same AOI, same id; a different AOI can never collide with it.
                    current_session_id = session_store.begin_session(
                        aoi_corners=[list(p.lat_lon_position) for p in calibration_points],
                        ground_scale=table_ground_scale,
                        homography=basemap_homography.matrix.tolist(),
                        global_k=global_model_scale_factor,
                    )
                    print(
                        f"Updated basemap homography from {len(calibration_points)} calibration points "
                        f"(1:{table_ground_scale:.1f} map, catalog geometry scaled by "
                        f"{global_model_scale_factor:.4f}, session {current_session_id})"
                    )
                    calibration_logger.info(
                        "CALIBRATION UPDATED from %s | session=%s | ground_scale=%.4f "
                        "| model_scale_factor=%.6f | points=%s | homography_matrix=%s | utm_offset=%s",
                        peer,
                        current_session_id,
                        table_ground_scale,
                        global_model_scale_factor,
                        json.dumps(
                            [
                                {
                                    "pixel_position": p.pixel_position,
                                    "lat_lon_position": p.lat_lon_position,
                                    "utm_position": p.utm_position,
                                }
                                for p in calibration_points
                            ]
                        ),
                        basemap_homography.matrix.tolist(),
                        basemap_homography.utm_offset,
                    )
                except (KeyError, ValueError) as exc:
                    print(f"Invalid map_calibration payload: {exc}")
                    calibration_logger.info(
                        "CALIBRATION REJECTED from %s | error=%s | raw_payload=%s",
                        peer,
                        exc,
                        payload,
                    )

            elif message_type == "clear_calibration":
                basemap_homography = None
                global_model_scale_factor = None
                current_session_id = None
                # Table positions belong to the calibration that produced them: a pixel read under
                # the old homography says nothing about where a block sits under the next one.
                latest_table_pixel_positions.clear()
                print("Cleared basemap homography; resuming raw marker output")
                calibration_logger.info("CALIBRATION CLEARED from %s", peer)

            elif message_type == "building_calibration":
                try:
                    _record_building_calibration(payload, peer)
                    print(
                        "Applied building_calibration for "
                        f"{payload.get('building_id')} (marker {payload.get('marker_id')}); run "
                        "building_catalog/publish-to-runtime.ps1 to make it the next boot default"
                    )
                except (KeyError, TypeError, ValueError) as exc:
                    # Never let a bad message close the socket: a dropped connection ends the
                    # operator's calibration session, which costs far more than a rejected nudge.
                    print(f"Rejected building_calibration: {exc}")
                    calibration_logger.info(
                        "BUILDING CALIBRATION REJECTED from %s | error=%s | raw_payload=%s",
                        peer,
                        exc,
                        payload,
                    )

            else:
                print(f"Unknown message type from web client: {message_type!r}")

    async def send_tracking_updates():
        async def send(snapshot: dict):
            global basemap_homography

            # Once the web client has sent map calibration points, convert
            # marker positions to GeoJSON; until then, send a plain dict
            # of markers.
            if basemap_homography is not None:
                markers_json = json.dumps(
                    markers_to_building_geojson(
                        snapshot, basemap_homography, scale=global_model_scale_factor or 1.0
                    )
                )
            else:
                markers_json = json.dumps(snapshot)

            print("Sending to web client:", markers_json)
            await websocket.send(markers_json)

        await stream_tracking_updates(send)  # 200ms interval between updates

    try:
        await asyncio.gather(receive_messages(), send_tracking_updates())
    except websockets.exceptions.ConnectionClosed as exc:
        print(f"Web client connection closed: {exc}")
    except Exception:
        print(f"Web client handler crashed for {peer}:")
        import traceback
        traceback.print_exc()
    finally:
        print(f"Web client disconnected: {peer}")


async def run_web_server():
    async with websockets.serve(handle_web_client, WEB_WS_HOST, WEB_WS_PORT):
        print(f"Listening for web client connections on {WEB_WS_HOST}:{WEB_WS_PORT}")
        await asyncio.Future()  # run forever


def setup_pixel_socket():
    global pixel_socket
    pixel_socket = socket_module.socket(socket_module.AF_INET, socket_module.SOCK_STREAM)
    print(f"Listening to socket connections on: {PIXEL_SOCKET_SETTINGS}")
    pixel_socket.bind(PIXEL_SOCKET_SETTINGS)
    pixel_socket.listen(1)
    pixel_socket.setblocking(False)


async def run_pixel_socket_server():
    while True:
        connection, client_address = await loop.sock_accept(pixel_socket)
        print(f"Unity client connected from: {client_address}")
        loop.create_task(send_tracking_matches_unity(connection))


async def send_tracking_matches_unity(connection):
    """Stream marker JSON to a Unity client.

    Always sends the raw marker JSON string, regardless of whether a basemap
    homography has been configured; the Unity client does not send anything
    back to the server.
    """
    async def send(snapshot: dict):
        markers_json = json.dumps(snapshot)
        print("Sending to Unity client:", markers_json)
        await loop.sock_sendall(connection, markers_json.encode("utf-8"))

    await stream_tracking_updates(send)


async def main(client: str, calibrate: bool = False):
    # Legacy calibration/camera helpers still use relative paths. Always resolve
    # them from the project directory so terminal and IDE launches behave alike.
    os.chdir(_SCRIPT_DIR)
    print(
        f"Loaded {len(physical_building_catalog['buildings'])} physical buildings "
        f"from {PHYSICAL_BUILDING_CATALOG_PATH}"
    )
    calibration_path = Path(_SCRIPT_DIR) / "calibration_markers.json"
    if calibrate:
        print("Calibration mode requested; rebuilding camera calibration...")
        calibration_data = calibrate_fixed_rig(calibration_path)
    else:
        print(f"Loading existing camera calibration from {calibration_path}")
        calibration_data = load_calibration_markers(str(calibration_path))

    # Initialize camera stitching from the selected calibration data.
    global stitching_setup
    stitching_setup = setup_camera_transforms(calibration_data)

    # Detection/stitching runs on its own thread so it never blocks the
    # asyncio event loop (which handles client I/O).
    start_detection_thread()

    print(f"waiting for {client} client to connect")

    if client == "unity":
        setup_pixel_socket()
        await run_pixel_socket_server()
    else:
        await run_web_server()


def shutdown_handler(sig, frame):
    """Handle graceful shutdown"""
    print("\nShutting down server...")
    if pixel_socket is not None:
        print("Closing socket...")
        pixel_socket.close()
    print("Stopping event loop...")
    loop.stop()
    sys.exit(0)


def parse_args():
    parser = argparse.ArgumentParser(description="COUP table object tracking server")
    parser.add_argument(
        "--client",
        choices=["unity", "web"],
        default="web",
        required=False,
        help="Which client to serve: 'unity' (raw TCP socket, marker JSON) or 'web' (websocket, geojson/dict)",
    )
    parser.add_argument(
        "--calibrate",
        action="store_true",
        help="Run the fixed-rig camera calibration before starting tracking",
    )
    return parser.parse_args()


def run_from_command_line():
    args = parse_args()

    logging.basicConfig(level=logging.INFO)

    # Register signal handlers
    signal.signal(signal.SIGINT, shutdown_handler)  # Ctrl+C
    signal.signal(signal.SIGTERM, shutdown_handler)  # Termination signal

    try:
        loop.run_until_complete(main(args.client, calibrate=args.calibrate))
    except KeyboardInterrupt:
        shutdown_handler(None, None)
    finally:
        if pixel_socket is not None:
            pixel_socket.close()
        loop.close()


# Guarded so the module can be imported (by tests, and by anything that wants
# `handle_web_client` without owning the process). `python server.py` is unchanged:
# argument parsing, signal handlers and the event loop all still run exactly as before.
if __name__ == "__main__":
    run_from_command_line()
