name: CI Pipeline

on:
  push:
    branches: [ main, "feat/*" ]
  pull_request:
    branches: [ main ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: '**/requirements-dev.txt'
    - run: make install
    - run: make -B test